spring:
  application:
    name: workflow-service
  datasource:
    url: jdbc:h2:mem:camunda-h2-database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      firstName: Demo
      lastName: User
    filter:
      create: All tasks
    webapp:
      index-redirect-enabled: true
    metrics:
      enabled: true
    authorization:
      enabled: true
    job-execution:
      enabled: true
    database:
      type: h2
      schema-update: true

server:
  port: 8080
  servlet:
    context-path: /workflow-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.camunda.bpm: DEBUG
    com.company.workflow: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/workflow-service.log