spring:
  application:
    name: workflow-service
  datasource:
    url: jdbc:mysql://mysql:3306/workflow_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: workflow_user
    password: workflow_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin123
      firstName: Admin
      lastName: User
    filter:
      create: All tasks
    webapp:
      index-redirect-enabled: true
    metrics:
      enabled: true
    authorization:
      enabled: true
    job-execution:
      enabled: true
    database:
      type: mysql
      schema-update: true

server:
  port: 8080
  servlet:
    context-path: /workflow-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.camunda.bpm: INFO
    com.company.workflow: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/workflow-service.log

file:
  upload:
    directory: /app/uploads