spring:
  application:
    name: company-management-system
  profiles:
    active: dev
  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/minicms
    username: dbuser
    password: 123qwe
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  flyway:
    enabled: true
    locations: filesystem:../scripts/db/migration
    baseline-on-migrate: true
    baseline-version: 0

# MyBatis Plus Configuration
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: org.max.cms

# Logging Configuration
logging:
  level:
    org.max.cms: DEBUG
    org.springframework.security: DEBUG
    com.baomidou.mybatisplus: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Server Configuration
server:
  port: 8080

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Authentication and Security Configuration
auth:
  security:
    exclude-paths:
      # 认证相关路径 - 支持多种路径格式
      - "/api/auth/login"
      - "/api/auth/register"
      
      # Swagger文档相关路径
      - "/swagger-ui/**"
      - "/swagger-ui.html"
      - "/swagger.html"
      - "/v3/api-docs/**"
      - "/swagger-resources/**"
      - "/webjars/**"
      
      # 健康检查相关路径
      - "/actuator/health"
      - "/actuator/info"
      
      # 静态资源路径
      - "/static/**"
      - "/public/**"

# Document Management Configuration (from asset-service)
document:
  storage-path: files
  max-file-size: 10485760  # 10MB
  allowed-types:
    - pdf
    - doc
    - docx
    - xls
    - xlsx
    - ppt
    - pptx
    - txt
    - jpg
    - jpeg
    - png
    - gif
    - bmp
    - zip
    - rar

# Service-specific configurations
services:
  bootloader:
    port: 8080
    context-path: /api
  asset-service:
    port: 8081
    context-path: /
  auth-service:
    port: 8082
    context-path: /
  user-service:
    port: 8083
    context-path: /