services:

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: minicms
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
